# Generated by Django 5.1.7 on 2025-03-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ('order',), 'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
