# Generated by Django 5.1.7 on 2025-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_footer_slug_alter_footer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='footer/icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
