# Generated by Django 5.1.7 on 2025-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',), 'verbose_name': 'Баннеры', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
