# Generated by Django 5.1.7 on 2025-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_user_alter_item_image_characteristic_item_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='items', to='users.customuser'),
        ),
    ]
